In [1]:
!pip install geopandas h3 osmnx geojson

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting geopandas
  Downloading geopandas-0.13.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 26.0 MB/s eta 0:00:00
Collecting h3
  Downloading h3-3.7.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 37.5 MB/s eta 0:00:00
Collecting osmnx
  Downloading osmnx-1.3.0-py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.1/93.1 kB 7.3 MB/s eta 0:00:00
Collecting geojson
  Downloading geojson-3.0.1-py3-none-any.whl (15 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from geopandas) (23.1)
Requirement already satisfied: shapely>=1.7.1 in /usr/local/lib/python3.10/dist-packages (from geopandas) (2.0.1)
Collecting fiona>=1.8.19
  Downloading Fiona-1.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 61.0 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from geopandas) (1.5.3)
Collecting pyproj>=3.0.1
  Downloading pyproj-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 62.5 MB/s eta 0:00:00
Requirement already satisfied: matplotlib>=3.5 in /usr/local/lib/python3.10/dist-packages (from osmnx) (3.7.1)
Collecting numpy>=1.23
  Downloading numpy-1.24.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 54.2 MB/s eta 0:00:00
Requirement already satisfied: networkx>=2.8 in /usr/local/lib/python3.10/dist-packages (from osmnx) (3.1)
Collecting requests>=2.28
  Downloading requests-2.30.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.5/62.5 kB 4.5 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8 in /usr/local/lib/python3.10/dist-packages (from osmnx) (2.8.2)
Requirement already satisfied: click~=8.0 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (8.1.3)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (23.1.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.19->geopandas) (2022.12.7)
Collecting munch>=2.3.2
  Downloading munch-2.5.0-py2.py3-none-any.whl (10 kB)
Collecting click-plugins>=1.0
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Collecting cligj>=0.5
  Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.5->osmnx) (8.4.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.5->osmnx) (4.39.3)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.5->osmnx) (3.0.9)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.5->osmnx) (1.0.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.5->osmnx) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.5->osmnx) (1.4.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.1.0->geopandas) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8->osmnx) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.28->osmnx) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.28->osmnx) (2.0.12)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.28->osmnx) (1.26.15)
Installing collected packages: h3, requests, pyproj, numpy, munch, geojson, cligj, click-plugins, fiona, geopandas, osmnx
  Attempting uninstall: requests
    Found existing installation: requests 2.27.1
    Uninstalling requests-2.27.1:
      Successfully uninstalled requests-2.27.1
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.4
    Uninstalling numpy-1.22.4:
      Successfully uninstalled numpy-1.22.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.3 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.3 which is incompatible.
Successfully installed click-plugins-1.1.1 cligj-0.7.2 fiona-1.9.3 geojson-3.0.1 geopandas-0.13.0 h3-3.7.6 munch-2.5.0 numpy-1.24.3 osmnx-1.3.0 pyproj-3.5.0 requests-2.30.0

In [2]:
import geopandas as gpd
import numpy as np
import json
import h3
import folium
import osmnx as ox
from shapely import wkt
from folium.plugins import HeatMap
from shapely.geometry import Polygon
from folium.plugins import MarkerCluster, HeatMap
import pandas as pd
from shapely.geometry import Polygon
from geojson import Feature, Point, FeatureCollection, Polygon
import plotly.express as px
from tqdm import tqdm

tqdm.pandas()
     

place_name = "Ступино, Московская область, RU"

RuntimeError: ignored

In [3]:
tags = {'amenity': True, 'landuse': ['retail', 'commercial'], 'shop': True, 'office': True, 'tourism': True} 

items = ox.geometries_from_place(place_name, tags)
items

<frozen importlib._bootstrap>:914: ImportWarning: APICoreClientInfoImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _PyDriveImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _OpenCVImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _BokehImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _AltairImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: APICoreClientInfoImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _PyDriveImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _OpenCVImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _BokehImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _AltairImportHook.find_spec() not found; falling back to find_module()

                                                              name tourism  \
element_type osmid
node         439193855                               Hotel Central  hostel
             440826527                                      Магнит     NaN
             446218402                                  BP Ступино     NaN
             446266808                                         NaN     NaN
             446266815                                         NaN     NaN
...                                                            ...     ...
relation     7146337                                           NaN     NaN
             10294944                   Церковь Николая Чудотворца     NaN
             10294945   Церковь Усекновения Головы Иоанна Предтечи     NaN
             10294946                  Церковь Сергия Радонежского     NaN
             10294947        Свято-Троицкий Белопесоцкий монастырь     NaN

                                                                 geometry  \
element_type osmid
node         439193855                          POINT (38.07850 54.88546)
             440826527                          POINT (38.05929 54.88626)
             446218402                          POINT (38.08016 54.90018)
             446266808                          POINT (38.07686 54.90918)
             446266815                          POINT (38.07028 54.89817)
...                                                                   ...
relation     7146337    POLYGON ((38.05169 54.88813, 38.05174 54.88835...
             10294944   POLYGON ((38.15092 54.85451, 38.15096 54.85453...
             10294945   POLYGON ((38.15079 54.85423, 38.15076 54.85425...
             10294946   POLYGON ((38.15054 54.85404, 38.15051 54.85405...
             10294947   POLYGON ((38.15063 54.85399, 38.15020 54.85373...

                               shop           amenity opening_hours operator  \
element_type osmid
node         439193855          NaN               NaN           NaN      NaN
             440826527  supermarket               NaN           NaN      NaN
             446218402          NaN              fuel          24/7       BP
             446266808          NaN          car_wash           NaN      NaN
             446266815      bicycle               NaN           NaN      NaN
...                             ...               ...           ...      ...
relation     7146337            NaN           parking           NaN      NaN
             10294944           NaN  place_of_worship           NaN      NaN
             10294945           NaN  place_of_worship           NaN      NaN
             10294946           NaN  place_of_worship           NaN      NaN
             10294947           NaN         monastery           NaN      NaN

                       addr:country website brand  ... name:signed  \
element_type osmid                                 ...
node         439193855          NaN     NaN   NaN  ...         NaN
             440826527          NaN     NaN   NaN  ...         NaN
             446218402          NaN     NaN   NaN  ...         NaN
             446266808          NaN     NaN   NaN  ...         NaN
             446266815          NaN     NaN   NaN  ...         NaN
...                             ...     ...   ...  ...         ...
relation     7146337            NaN     NaN   NaN  ...         NaN
             10294944           NaN     NaN   NaN  ...         NaN
             10294945           NaN     NaN   NaN  ...         NaN
             10294946           NaN     NaN   NaN  ...         NaN
             10294947           NaN     NaN   NaN  ...         NaN

                       building:levels:underground toilets:access toilets:fee  \
element_type osmid
node         439193855                         NaN            NaN         NaN
             440826527                         NaN            NaN         NaN
             446218402                         NaN            NaN         NaN
             446266808                         NaN            NaN         NaN
             446266815                         NaN            NaN         NaN
...                                            ...            ...         ...
relation     7146337                           NaN            NaN         NaN
             10294944                          NaN            NaN         NaN
             10294945                          NaN            NaN         NaN
             10294946                          NaN            NaN         NaN
             10294947                          NaN            NaN         NaN

                       fire_station:type building:part  \
element_type osmid
node         439193855               NaN           NaN
             440826527               NaN           NaN
             446218402               NaN           NaN
             446266808               NaN           NaN
             446266815               NaN           NaN
...                                  ...           ...
relation     7146337                 NaN           NaN
             10294944                NaN           NaN
             10294945                NaN           NaN
             10294946                NaN           NaN
             10294947                NaN           NaN

                                                                     ways  \
element_type osmid
node         439193855                                                NaN
             440826527                                                NaN
             446218402                                                NaN
             446266808                                                NaN
             446266815                                                NaN
...                                                                   ...
relation     7146337         [402264216, 485673283, 485673284, 485673285]
             10294944                   [745106457, 745106456, 745106454]
             10294945                   [745106463, 745106458, 745106461]
             10294946        [745106460, 745106459, 745106462, 745106458]
             10294947   [745106460, 126127635, 745106456, 745106455, 7...

                                type health_facility:type place_of_worship
element_type osmid
node         439193855           NaN                  NaN              NaN
             440826527           NaN                  NaN              NaN
             446218402           NaN                  NaN              NaN
             446266808           NaN                  NaN              NaN
             446266815           NaN                  NaN              NaN
...                              ...                  ...              ...
relation     7146337    multipolygon                  NaN              NaN
             10294944   multipolygon                  NaN              NaN
             10294945   multipolygon                  NaN              NaN
             10294946   multipolygon                  NaN              NaN
             10294947   multipolygon                  NaN        monastery

[1197 rows x 159 columns]

In [4]:
items.shop.value_counts()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

convenience       53
supermarket       22
kiosk             19
outpost           15
car_repair        14
clothes           11
hardware          10
mall               9
mobile_phone       9
hairdresser        8
doityourself       7
furniture          6
cosmetics          4
car_parts          4
electronics        4
yes                3
butcher            3
wine               3
bicycle            3
alcohol            3
shoes              3
pet                2
stationery         2
sports             2
jewelry            2
books              2
second_hand        2
bakery             2
hunting            2
beauty             2
ticket             2
toys               2
beverages          2
locksmith          1
kitchen            1
paint              1
travel_agency      1
fishing            1
copyshop           1
medical_supply     1
greengrocer        1
e-cigarette        1
computer           1
bookmaker          1
florist            1
Авокадо            1
farm               1
coffee             1
optician           1
variety_store      1
dry_cleaning       1
photo              1
outdoor            1
shoe_repair        1
car                1
newsagent          1
Name: shop, dtype: int64

In [26]:
shops = {i: ix for ix, i  in enumerate(dict(items.shop.value_counts()[:]).keys())}
shops_inv = {ix: i for ix, i  in enumerate(dict(items.shop.value_counts()[:]).keys())}

In [6]:
# list(shops.keys())

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [27]:
one_hot_shop = pd.get_dummies(items['shop'])
df_shops = one_hot_shop[list(shops.keys())]#.groupby()

In [28]:
amenities = {i: ix for ix, i  in enumerate(dict(items.amenity.value_counts()[:]).keys())}

In [29]:
tourism = {i: ix for ix, i  in enumerate(dict(items.tourism.value_counts()[:]).keys())}

In [30]:
office = {i: ix for ix, i  in enumerate(dict(items.office.value_counts()[:]).keys())}

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [9]:
one_hot_amenity = pd.get_dummies(items['amenity'])
df_amenity = one_hot_amenity[list(amenities.keys())]#.groupby()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [31]:
one_hot_tourism = pd.get_dummies(items['tourism'])
df_tourism = one_hot_tourism[list(tourism.keys())]#.groupby()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [36]:
one_hot_office = pd.get_dummies(items['office'])
df_office = one_hot_office[list(office.keys())]#.groupby()

In [32]:
df1 = pd.merge(df_amenity, df_shops, left_on='osmid', right_on='osmid')

In [33]:
df2 = pd.merge(df1, df_tourism, left_on='osmid', right_on='osmid')

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [37]:
df3 = pd.merge(df2, df_office, left_on='osmid', right_on='osmid')

In [18]:
df_h3 = pd.read_csv('locations.csv')

In [21]:
df3 = df_h3[["osmid","h3_cell"]]

In [38]:
df = pd.merge(df1, df3, left_on='osmid', right_on='osmid')

In [23]:
df_emb = df.groupby('h3_cell').sum()

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [39]:
df_emb

,osmid,parking,bench,waste_disposal,waste_basket,kindergarten,cafe,school,atm,pharmacy,...,convenience,supermarket,kiosk,outpost,car_repair,clothes,hardware,mall,mobile_phone,hairdresser
h3_cell,,,,,,,,,,,,,,,,,,,,,
882da99209fffff,322563818221,25,22,11,3,1,0,1,1,0,...,3,1,0,2,4,2,0,0,0,1
882da99219fffff,484674317559,35,7,7,0,1,5,1,0,2,...,9,6,2,4,1,1,1,3,0,1
882da99245fffff,25466467304,5,0,1,0,0,0,0,0,0,...,0,0,0,0,3,0,1,0,0,0
882da99247fffff,49384359003,15,1,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
882da99255fffff,464085327724,38,18,13,10,4,0,1,0,1,...,6,1,0,1,2,4,0,0,0,1
882da99257fffff,715822876619,81,9,28,0,4,3,1,7,3,...,12,3,9,2,1,1,4,2,3,0
882da99269fffff,20605008180,1,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
882da992c9fffff,184533726031,14,0,13,0,2,1,2,0,0,...,1,1,0,2,0,1,1,0,0,0
882da992d9fffff,13248765686,2,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
882da99645fffff,10417394008,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
882da99651fffff,10086317898,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
882da99653fffff,12441854924,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
882dad2995fffff,335906715,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
882dad2997fffff,13621955386,2,0,0,0,0,1,0,1,0,...,1,0,0,0,0,0,0,0,0,0
882dad29a9fffff,2206806102,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
882dad29abfffff,1341498631,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
882dad29b9fffff,2627083975,3,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
882dad2d25fffff,913764112660,35,68,11,1,7,2,2,2,4,...,3,5,4,1,0,2,2,2,5,2
882dad2d27fffff,591841649403,32,32,22,0,6,4,5,2,3,...,7,3,3,1,1,0,0,2,1,2
882dad2d33fffff,14195913295,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
882dad2d35fffff,50743668118,3,0,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
882dad2d37fffff,17612512959,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
882dad2d83fffff,57630582465,2,7,0,2,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
882dad2d85fffff,28610006097,0,0,2,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
882dad2d87fffff,34283432093,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
882dad2d93fffff,26756808332,2,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
882dad2d95fffff,57674316344,2,5,0,2,0,0,0,0,0,...,2,0,0,1,0,0,0,0,0,1
882dad2d97fffff,68099417154,5,0,0,0,0,0,0,0,1,...,1,0,0,0,0,0,1,0,0,0
882dad2de3fffff,8640547120,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
882dad2de7fffff,124681480786,0,8,0,8,0,0,0,1,0,...,1,2,0,1,0,0,0,0,0,0

In [40]:
list(df_emb.columns)

['osmid',
 'parking',
 'bench',
 'waste_disposal',
 'waste_basket',
 'kindergarten',
 'cafe',
 'school',
 'atm',
 'pharmacy',
 'bank',
 'convenience',
 'supermarket',
 'kiosk',
 'outpost',
 'car_repair',
 'clothes',
 'hardware',
 'mall',
 'mobile_phone',
 'hairdresser']

In [41]:
df.to_csv('locs_emb.csv')